import clsx from 'clsx'
import { useEffect, useState } from 'react'
import { AlertTriangle, ArchiveRestore, CheckCircle2, Clock, Cloud, Database, Download, Upload } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DEFAULT_FRESHNESS, useStore } from '../lib/store'
import { duplicateTransactionIds, isClosingSale } from '../lib/transaction-review'
import { listBackups, loadBackup, saveBackup, type BackupMetadata } from '../lib/api'
import { PageHeader, Button, StatCard } from '../components/ui'
import { useConfirmDialog } from '../components/ConfirmDialog'
import { useToast } from '../components/Toast'
import { relTime } from '../lib/format'

const ageDays = (at: string, now: string) => at ? Math.max(0, Math.floor((new Date(now).getTime() - new Date(at).getTime()) / 86_400_000)) : null
const latest = (rows: { importedAt: string }[]) => rows.reduce((value, row) => row.importedAt > value ? row.importedAt : value, '')

export default function DataQuality() {
  const { data, rollbackImport, clearCsvAuthority, setFreshnessThresholds, restoreBackup } = useStore()
  const dialogs = useConfirmDialog(); const { push } = useToast()
  const duplicateCount = duplicateTransactionIds(data.transactions).size
  const missingPl = data.transactions.filter((row) => isClosingSale(row) && row.pl == null).length
  const unassigned = data.transactions.filter((row) => row.type === 'Dividend' && !row.symbol).length
  const other = data.transactions.filter((row) => row.type === 'Other').length
  const conflicts = data.lastSyncChanges?.csvConflicts ?? 0
  const thresholds = data.freshnessThresholds ?? DEFAULT_FRESHNESS
  const positionAge = ageDays(latest(data.csvPositionAuthority ?? []), data.lastSyncAt)
  const transactionAge = ageDays(latest(data.csvTransactionAuthority ?? []), data.lastSyncAt)
  const realizedAge = ageDays(latest((data.csvTransactionAuthority ?? []).filter((row) => row.transaction.pl != null)), data.lastSyncAt)
  const stale = (positionAge != null && positionAge >= thresholds.positions) || (transactionAge != null && transactionAge >= thresholds.transactions) || (realizedAge != null && realizedAge >= thresholds.realizedPl)
  const exceptions = duplicateCount + missingPl + unassigned + other + conflicts + (stale ? 1 : 0)
  const confidence = exceptions === 0 ? 'High' : exceptions <= 5 ? 'Medium' : 'Low'
  const [backups, setBackups] = useState<BackupMetadata[]>([]); const [backupBusy, setBackupBusy] = useState(false)
  useEffect(() => { void listBackups().then(setBackups) }, [])

  const downloadBackup = () => { const blob = new Blob([JSON.stringify({ format: 'simonfire-backup', exportedAt: new Date().toISOString(), data }, null, 2)], { type: 'application/json' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = `simonfire-backup-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(anchor.href) }
  const restoreFile = (file?: File) => { if (!file) return; void file.text().then(async (text) => { const parsed = JSON.parse(text); const backup = parsed?.format === 'simonfire-backup' ? parsed.data : parsed; if (await dialogs.confirm('Restore backup', `Restore ${backup?.positions?.length ?? 0} positions and ${backup?.transactions?.length ?? 0} transactions from ${file.name}?`, 'Restore')) restoreBackup(backup) }).catch(() => push('Invalid backup file', 'error', 'Choose a SimonFIRE JSON backup.')) }
  const createServerBackup = async () => { setBackupBusy(true); const saved = await saveBackup(data, 'Manual checkpoint'); setBackups(await listBackups()); setBackupBusy(false); push(saved ? 'Checkpoint saved' : 'Backup failed', saved ? 'success' : 'error') }
  const restoreServer = async (metadata: BackupMetadata) => { if (!await dialogs.confirm('Restore server backup', `Restore the checkpoint from ${new Date(metadata.createdAt).toLocaleString()}?`, 'Restore')) return; const backup = await loadBackup(metadata.id); if (backup) restoreBackup(backup); else push('Backup unavailable', 'error') }
  const rollback = async (id: string) => { if (await dialogs.confirm('Roll back CSV import', 'Remove this import batch as an authoritative source? Sync Schwab afterward to refresh affected records.', 'Roll back')) rollbackImport(id) }
  const clearAuthority = async (mask: string, kind: 'positions'|'transactions'|'realizedPl') => { if (await dialogs.confirm('Clear CSV authority', `Stop using ${kind === 'realizedPl' ? 'realized P/L' : kind} CSV data for account ····${mask}?`, 'Clear authority')) clearCsvAuthority(mask, kind) }

  return <div><PageHeader title="Data Quality" subtitle="Sources, freshness, exceptions, imports, and recoverability" right={<><Button onClick={downloadBackup}><Download size={15}/> Export backup</Button><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm"><Upload size={15}/> Restore backup<input aria-label="Restore backup file" type="file" accept="application/json,.json" className="hidden" onChange={(event) => restoreFile(event.target.files?.[0])}/></label></>}/>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Overall confidence" value={confidence} good={confidence === 'High'} note={`${exceptions} item${exceptions === 1 ? ' needs' : 's need'} attention`}/><Metric label="CSV position snapshot" value={positionAge == null ? 'Not uploaded' : `${positionAge} days old`} good={positionAge != null && positionAge < thresholds.positions} note="Cost-basis source"/><Metric label="Latest API sync" value={relTime(data.lastSyncAt)} good={data.source === 'live'} note="Balances, inventory, prices, and orders"/></div>
    <Section title="Needs attention" subtitle="Exceptions appear only when they can affect a calculation or require review."><div className="grid gap-2 sm:grid-cols-2">{duplicateCount > 0 && <Issue label={`${duplicateCount} potential duplicate records`} to="/transactions"/>}{missingPl > 0 && <Issue label={`${missingPl} closing sales missing P/L`} to="/transactions"/>}{unassigned > 0 && <Issue label={`${unassigned} dividends missing symbols`} to="/dividends"/>}{other > 0 && <Issue label={`${other} uncategorized transactions`} to="/transactions"/>}{conflicts > 0 && <Issue label={`${conflicts} API values differed from CSV values`}/>} {stale && <Issue label="One or more CSV accounting snapshots are stale"/>}{exceptions === 0 && <div className="flex items-center gap-2 text-sm text-pos"><CheckCircle2 size={16}/> No material data exceptions found.</div>}</div></Section>
    {(data.lastSyncChanges?.csvConflictDetails?.length ?? 0) > 0 && <section className="card mt-5 overflow-hidden p-0"><div className="p-5"><h2 className="font-semibold">API / CSV field reconciliation</h2><p className="mt-1 text-xs text-faint">Accounting fields use CSV; live inventory and market fields use API.</p></div><div className="overflow-x-auto"><table aria-label="API and CSV conflicts" className="w-full min-w-[680px] text-xs"><thead><tr className="border-y border-border-soft text-left text-faint"><th className="px-4 py-2">Record</th><th className="px-4 py-2">Field</th><th className="px-4 py-2">API</th><th className="px-4 py-2">CSV</th><th className="px-4 py-2">Winner</th></tr></thead><tbody>{data.lastSyncChanges!.csvConflictDetails!.map((row,index) => <tr key={`${row.record}-${row.field}-${index}`} className="border-b border-border-soft"><td className="px-4 py-2 font-medium">{row.record}</td><td className="px-4 py-2 text-muted">{row.field}</td><td className="max-w-48 truncate px-4 py-2 text-faint">{row.apiValue}</td><td className="max-w-48 truncate px-4 py-2">{row.csvValue}</td><td className="px-4 py-2 font-semibold text-[#7fb5ff]">{row.winner}</td></tr>)}</tbody></table></div></section>}
    <Section title="CSV authority by account" subtitle="Remove a stale authority source without deleting the live Schwab account."><div className="space-y-2">{data.accounts.map((account) => <div key={account.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-border-soft p-3 text-xs"><strong className="mr-auto">{account.name} ····{account.mask}</strong><button onClick={() => clearAuthority(account.mask,'positions')} className="text-brand">Clear positions</button><button onClick={() => clearAuthority(account.mask,'transactions')} className="text-brand">Clear transactions</button><button onClick={() => clearAuthority(account.mask,'realizedPl')} className="text-brand">Clear realized P/L</button></div>)}</div></Section>
    <Section title="Freshness controls" subtitle="Choose when accounting exports should be refreshed."><div className="grid gap-3 sm:grid-cols-3"><Threshold label="Positions CSV" value={thresholds.positions} onChange={(positions) => setFreshnessThresholds({ ...thresholds, positions })}/><Threshold label="Transactions CSV" value={thresholds.transactions} onChange={(transactions) => setFreshnessThresholds({ ...thresholds, transactions })}/><Threshold label="Realized P/L CSV" value={thresholds.realizedPl} onChange={(realizedPl) => setFreshnessThresholds({ ...thresholds, realizedPl })}/></div></Section>
    <Section title="Import history" subtitle="Authoritative CSV batches can be rolled back safely."><div className="divide-y divide-border-soft">{(data.importHistory ?? []).map((entry) => <div key={entry.id} className="flex flex-wrap items-center gap-3 py-3 text-xs"><Clock size={14} className="text-faint"/><div className="min-w-0 flex-1"><div className="truncate font-medium">{entry.files.join(', ')}</div><div className="text-faint">{relTime(entry.importedAt)} · {entry.positions} positions · {entry.transactions} transactions · {entry.realizedPl} P/L values</div></div><span className={entry.status === 'active' ? 'text-pos' : 'text-faint'}>{entry.status === 'active' ? 'Active' : 'Rolled back'}</span>{entry.status === 'active' && <button onClick={() => rollback(entry.id)} className="inline-flex items-center gap-1 font-semibold text-[#e1c887]"><ArchiveRestore size={13}/> Roll back</button>}</div>)}{!(data.importHistory?.length) && <Empty text="No CSV imports recorded yet."/>}</div></Section>
    <section className="card mt-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Cloud size={16} className="text-brand"/><h2 className="font-semibold">Rotating server backups</h2></div><p className="mt-1 text-xs text-faint">Daily snapshots retain the seven newest restore points.</p></div><Button disabled={backupBusy} onClick={createServerBackup}>{backupBusy ? 'Saving…' : 'Create checkpoint'}</Button></div><div className="mt-4 divide-y divide-border-soft">{backups.map((backup) => <div key={backup.id} className="flex items-center gap-3 py-3 text-xs"><div className="min-w-0 flex-1"><div className="font-medium">{backup.reason}</div><div className="text-faint">{relTime(backup.createdAt)} · {backup.positions} positions · {backup.transactions} transactions</div></div><button onClick={() => restoreServer(backup)} className="font-semibold text-brand">Preview &amp; restore</button></div>)}{!backups.length && <Empty text="No server backups are available yet."/>}</div></section>
    <Section title="Calculation trust" subtitle="Authoritative source order"><div className="grid gap-2 text-xs sm:grid-cols-2"><Trust label="Balances and equity" source="Live Schwab API"/><Trust label="Current quantities and prices" source="Live Schwab API"/><Trust label="Cost basis" source={positionAge == null ? 'Schwab API until CSV upload' : 'Latest Positions CSV'}/><Trust label="Historical transactions and realized P/L" source="CSV when matched; API supplements gaps"/></div></Section>
  </div>
}
function Section({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="card mt-5 p-5"><div className="flex items-center gap-2"><Database size={16} className="text-brand"/><h2 className="font-semibold">{title}</h2></div><p className="mt-1 text-xs text-faint">{subtitle}</p><div className="mt-4">{children}</div></section> }
function Metric({ label,value,good,note }: { label:string; value:string; good:boolean; note:string }) { return <StatCard label={label} value={value} sub={note} valueClass={clsx('!font-sans', good ? 'text-pos' : 'text-[#e1c887]')} right={good ? <CheckCircle2 size={15} className="text-pos"/> : <AlertTriangle size={15} className="text-[#e1c887]"/>}/> }
function Issue({ label,to }: { label:string; to?:string }) { const body = <><AlertTriangle size={14} className="text-[#e1c887]"/><span>{label}</span></>; return to ? <Link to={to} className="flex items-center gap-2 rounded-xl border border-[#e1c887]/15 p-3 text-xs">{body}</Link> : <div className="flex items-center gap-2 rounded-xl border border-[#e1c887]/15 p-3 text-xs">{body}</div> }
function Threshold({ label,value,onChange }: { label:string; value:number; onChange:(value:number)=>void }) { return <label className="rounded-xl border border-border-soft p-3 text-xs text-muted">{label}<div className="mt-2 flex items-center gap-2"><input aria-label={`${label} warning days`} type="number" min="1" max="365" value={value} onChange={(event) => onChange(Math.max(1,Number(event.target.value)||1))} className="num w-20 rounded-lg border border-border bg-surface-2 px-2 py-1.5 text-ink"/><span className="text-faint">days</span></div></label> }
function Trust({ label,source }: { label:string; source:string }) { return <div className="flex items-center justify-between gap-3 rounded-lg bg-surface-2 px-3 py-2"><span className="text-muted">{label}</span><span className="text-right font-medium">{source}</span></div> }
function Empty({ text }: { text:string }) { return <div className="py-6 text-center text-sm text-faint">{text}</div> }
