import { useState } from 'react'
import { availableMonths, bridgeTransactions, type MonthClose } from '../lib/calc'
import type { Account, Position, Transaction } from '../lib/types'
import { monthLabel, shortDate, usd } from '../lib/format'
import { Waterfall } from './Charts'
import { TransactionDrawer } from './TransactionDrawer'

export function EquityBridge({ close, transactions, positions, accounts, scope, chart = false }: {
  close: MonthClose; transactions: Transaction[]; positions: Position[]; accounts: Account[]; scope: string; chart?: boolean
}) {
  const [selected, setSelected] = useState<number | null>(null)
  const [transactionId, setTransactionId] = useState<string | null>(null)
  const step = selected == null ? null : close.bridge[selected]
  const monthly = transactions.filter((t) => t.date.slice(0, 7) === close.ym)
  const rows = bridgeTransactions(transactions, close.ym, selected)
  const scopedAccounts = accounts.filter((a) => scope === 'all' || a.id === scope)
  const byTicker = new Map<string, number>()
  for (const p of positions) byTicker.set(p.symbol, (byTicker.get(p.symbol) ?? 0) + p.shares * p.lastPrice)
  const currentClosing = close.ym === availableMonths(transactions)[0]
  const accountName = (id: string) => accounts.find((a) => a.id === id)?.name ?? id
  const total = rows.reduce((n, r) => n + r.value, 0)
  return <>
    {chart && <Waterfall steps={close.bridge} height={300} onStepClick={setSelected} />}
    <p className="mt-2 text-xs text-muted">Select a bridge value to see its breakdown.</p>
    <div className={chart ? 'mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3' : 'mt-3 divide-y divide-border-soft'}>
      {close.bridge.map((row, index) => <button key={row.label} type="button" aria-expanded={selected === index} aria-controls="equity-bridge-detail" onClick={() => setSelected(selected === index ? null : index)} className={`flex w-full items-center justify-between gap-3 rounded-lg p-2 text-left text-xs hover:bg-white/[.06] focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand ${selected === index ? 'bg-white/[.08] text-ink' : 'text-muted'}`}><span>{row.label}</span><span className="num">{usd(row.value, { sign: row.kind !== 'base' && row.kind !== 'total' })}</span></button>)}
    </div>
    {step && <section id="equity-bridge-detail" aria-label={`${step.label} breakdown`} className="mt-4 rounded-xl border border-border-soft p-4">
      <div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{step.label}: {usd(step.value, { sign: true })}</h3><p className="mt-1 text-xs text-muted">{monthLabel(close.ym)}</p></div><button type="button" onClick={() => setSelected(null)} className="text-xs text-muted hover:text-ink">Close</button></div>
      {(selected === 1 || selected === 2 || selected === 3) && <>
        <p className="mt-3 text-xs text-muted">{selected === 3 ? 'Realized profit or loss, not sale proceeds. Missing P/L contributes $0 to this bridge.' : selected === 2 ? 'Income less operating expenses, including withdrawals, bill payments, margin interest, fees, and withholding.' : 'Recorded contributions for this month.'}</p>
        {rows.length === 0 ? <p className="mt-3 text-sm text-muted">No contributing transactions in this month.</p> : <div className="mt-3 max-h-80 overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="text-muted"><th className="p-2">Date / account</th><th className="p-2">Ticker / transaction</th><th className="p-2 text-right">{selected === 3 ? 'Realized P/L' : 'Amount'}</th></tr></thead><tbody>{rows.map(({ transaction: t, value }) => <tr key={t.id} className="border-t border-border-soft"><td className="p-2 whitespace-nowrap">{shortDate(t.date)}<div className="text-faint">{accountName(t.accountId)}</div></td><td className="p-2"><button type="button" onClick={() => setTransactionId(t.id)} className="text-left text-brand underline">{t.symbol || t.type}</button><div className="mt-1 text-faint">{t.description || t.type}</div>{selected === 3 && t.plEstimated && <div className="text-faint">Estimated P/L</div>}{selected === 3 && t.pl == null && <div className="text-[#f0a94a]">P/L missing</div>}</td><td className={`num p-2 text-right whitespace-nowrap ${value < 0 ? 'text-neg' : 'text-pos'}`}>{usd(value, { sign: true })}</td></tr>)}</tbody><tfoot><tr><th colSpan={2} className="p-2">Transaction total</th><td className="num p-2 text-right">{usd(total, { sign: true })}</td></tr></tfoot></table></div>}
      </>}
      {selected === 4 && <p className="mt-3 text-sm text-muted">This bridge currently uses a fixed $0 for accounts added. It does not track account-opening balances, so there are no supporting transactions.</p>}
      {selected === 5 && <p className="mt-3 text-sm text-muted">This value is generated by a placeholder market-movement formula, not historical prices or transactions. A ticker-level breakdown is unavailable; this is not measured investment performance.</p>}
      {selected === 0 && <><p className="mt-3 text-sm text-muted">Opening equity is reconstructed backward from closing equity by subtracting the changes below. It is not a recorded historical balance and includes the placeholder Market &amp; Other amount.</p><dl className="mt-3 space-y-2 text-xs"><Detail label="Closing equity" value={close.closing}/>{close.bridge.slice(1, -1).map((r) => <Detail key={r.label} label={`Less ${r.label}`} value={-r.value}/>)}<Detail label="Opening equity" value={close.opening}/></dl></>}
      {selected === 6 && (currentClosing ? <><p className="mt-3 text-xs text-muted">Current holdings at their latest prices, plus cash, less margin debt. These are current values, not a historical month-end snapshot.</p><dl className="mt-3 max-h-80 space-y-2 overflow-auto text-xs">{[...byTicker].sort((a, b) => b[1] - a[1]).map(([symbol, value]) => <Detail key={symbol} label={symbol} value={value}/>)}{scopedAccounts.map((a) => <div key={a.id}><Detail label={`${a.name} · cash`} value={a.cash}/><Detail label={`${a.name} · margin debt`} value={-a.marginBalance}/></div>)}<Detail label="Closing equity" value={close.closing}/></dl></> : <p className="mt-3 text-sm text-muted">This historical closing balance is reconstructed backward from current equity using later months’ contributions, operating cash flow, realized P/L, and placeholder market movements. Historical holdings snapshots are unavailable, so it cannot be attributed to tickers reliably.</p>)}
    </section>}
    <TransactionDrawer txn={monthly.find((t) => t.id === transactionId) ?? null} onClose={() => setTransactionId(null)}/>
  </>
}

function Detail({ label, value }: { label: string; value: number }) {
  return <div className="flex justify-between gap-3 py-1"><dt className="text-muted">{label}</dt><dd className="num">{usd(value, { sign: true })}</dd></div>
}
