import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Bell, CheckCircle2, Command, Search } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../lib/store'
import { isClosingSale } from '../lib/transaction-review'
import { usePersistentState } from '../lib/persistent-state'
import { Modal } from './Modal'

const pages = [['Today','/'],['Positions','/positions'],['Transactions','/transactions'],['Dividends','/dividends'],['Cash Flow','/cash-flow'],['Historical Value','/history'],['Allocation & Puts','/allocation'],['Reports','/reports'],['Data Quality','/data-quality'],['Preferences','/preferences'],['Connections','/connections']]
type Alert = { id: string; label: string; detail: string; to: string }

export function PremiumTools() {
  const { data } = useStore(); const navigate = useNavigate()
  const [palette, setPalette] = useState(false); const [notifications, setNotifications] = useState(false); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(0)
  const [notificationState, setNotificationState] = usePersistentState<Record<string, { read?: boolean; snoozedUntil?: string; dismissed?: boolean }>>('simonfire.notifications', {})
  useEffect(() => { const key = (event: KeyboardEvent) => { if (((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') || (event.key === '/' && !['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement).tagName))) { event.preventDefault(); setPalette(true) } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [])
  const items = useMemo(() => { const q = query.trim().toLowerCase(); return [...pages.map(([label,to]) => ({ label, detail: 'Page', to })), ...data.positions.map((row) => ({ label: row.symbol, detail: `${row.name} · Position`, to: '/positions' })), ...data.transactions.slice(0,300).map((row) => ({ label: row.symbol ?? row.type, detail: `${row.date} · ${row.description}`, to: '/transactions' }))].filter((item) => !q || `${item.label} ${item.detail}`.toLowerCase().includes(q)).slice(0,30) }, [data.positions, data.transactions, query])
  useEffect(() => setSelected(0), [query])
  const allAlerts = useMemo(() => { const result: Alert[] = []; const missingPl = data.transactions.filter((row) => isClosingSale(row) && row.pl == null).length; const unassigned = data.transactions.filter((row) => row.type === 'Dividend' && !row.symbol).length; const failed = data.connections.filter((row) => row.status === 'Error').length; const puts = (data.hedgeRolls ?? []).filter((row) => row.status === 'active' && row.rollDate <= data.lastSyncAt.slice(0,10)).length; if (missingPl) result.push({ id: 'missing-pl', label: `${missingPl} sales missing P/L`, detail: 'Upload realized gain/loss or enter cost basis.', to: '/data-quality' }); if (unassigned) result.push({ id: 'unassigned-dividends', label: `${unassigned} dividends unassigned`, detail: 'Assign symbols to improve projections.', to: '/dividends' }); if (puts) result.push({ id: 'put-rolls', label: `${puts} protective puts need roll review`, detail: 'Review current value and recommendation.', to: '/allocation' }); if (failed) result.push({ id: 'connection-errors', label: `${failed} connection errors`, detail: 'Reconnect Schwab to restore sync.', to: '/connections' }); if ((data.lastSyncChanges?.csvConflicts ?? 0) > 0) result.push({ id: 'csv-conflicts', label: `${data.lastSyncChanges!.csvConflicts} API/CSV differences`, detail: 'CSV accounting values won during reconciliation.', to: '/data-quality' }); return result }, [data])
  const now = data.lastSyncAt; const alerts = allAlerts.filter((alert) => !notificationState[alert.id]?.dismissed && (!notificationState[alert.id]?.snoozedUntil || notificationState[alert.id].snoozedUntil! <= now)); const unread = alerts.filter((alert) => !notificationState[alert.id]?.read).length
  const go = (to: string) => { setPalette(false); setNotifications(false); setQuery(''); navigate(to) }
  const updateAlert = (id: string, patch: Record<string, unknown>) => setNotificationState({ ...notificationState, [id]: { ...notificationState[id], ...patch } })
  return <><div className="flex items-center gap-1.5"><button onClick={() => setPalette(true)} aria-label="Open command palette" title="Search (⌘K)" className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-bg/90 text-faint shadow-lg hover:text-ink"><Command size={15}/></button><button onClick={() => { setNotifications(true); const next = { ...notificationState }; alerts.forEach((alert) => { next[alert.id] = { ...next[alert.id], read: true } }); setNotificationState(next) }} aria-label={`${unread} unread notifications`} title="Notifications" className="relative grid h-9 w-9 place-items-center rounded-lg border border-border bg-bg/90 text-faint shadow-lg hover:text-ink"><Bell size={15}/>{unread > 0 && <span className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-[#e1c887] px-1 text-[9px] font-bold text-black">{unread}</span>}</button></div>
    <Modal open={palette} onClose={() => setPalette(false)} title="Search SimonFIRE" subtitle="Pages, holdings, transactions, and actions · ⌘K or /" width="max-w-xl"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-faint"/><input autoFocus role="combobox" aria-expanded="true" aria-controls="command-results" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'ArrowDown') { event.preventDefault(); setSelected((value) => Math.min(items.length - 1, value + 1)) } if (event.key === 'ArrowUp') { event.preventDefault(); setSelected((value) => Math.max(0, value - 1)) } if (event.key === 'Enter' && items[selected]) go(items[selected].to) }} placeholder="Search anything…" className="w-full rounded-xl border border-border bg-surface-2 py-3 pl-10 pr-3 text-sm outline-none focus:border-brand"/></div><div id="command-results" role="listbox" className="mt-3 max-h-80 overflow-auto divide-y divide-border-soft">{items.map((item,index) => <button role="option" aria-selected={selected === index} key={`${item.to}-${item.label}-${index}`} onMouseEnter={() => setSelected(index)} onClick={() => go(item.to)} className={selected === index ? 'flex w-full items-center justify-between gap-3 bg-surface-2 px-2 py-3 text-left' : 'flex w-full items-center justify-between gap-3 px-2 py-3 text-left hover:bg-surface-2'}><span className="truncate text-sm font-medium">{item.label}</span><span className="max-w-[60%] truncate text-xs text-faint">{item.detail}</span></button>)}{!items.length && <div className="py-8 text-center text-sm text-faint">No matching pages or records.</div>}</div></Modal>
    <Modal open={notifications} onClose={() => setNotifications(false)} title="Notifications" subtitle="Read, snooze, or dismiss items that need attention" width="max-w-lg"><div className="space-y-2">{alerts.map((alert) => <div key={alert.id} className="rounded-xl border border-border-soft p-3"><button onClick={() => go(alert.to)} className="flex w-full items-start gap-3 text-left"><AlertTriangle size={16} className="mt-0.5 text-[#e1c887]"/><span><strong className="block text-sm">{alert.label}</strong><span className="text-xs text-faint">{alert.detail}</span></span></button><div className="mt-2 flex justify-end gap-3 text-[10px]"><button onClick={() => updateAlert(alert.id, { snoozedUntil: new Date(new Date(now).getTime() + 86_400_000).toISOString() })} className="text-muted">Snooze 1 day</button><button onClick={() => updateAlert(alert.id, { dismissed: true })} className="text-faint">Dismiss</button></div></div>)}{!alerts.length && <div className="flex items-center gap-2 py-8 text-sm text-pos"><CheckCircle2 size={17}/> You’re caught up. No action is needed.</div>}</div></Modal></>
}
